### ISSUE TITLE
Wait Alert keeps popping up

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#77] opened 2023-08-04 17:01 UTC
All users have been experiencing long await alerts all morning that I am pretty sure are coming from the Toolkit

<img width="600" alt="image" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/7302bc30-c4b1-4eec-8494-0fcd08f056db">

**Comment by djbbiz** [comment] 2023-08-04 17:35
I am getting this message every few minutes now. Any idea why?

**Comment by djbbiz** [comment] 2023-08-04 18:07
I have isolated the problem to some custom javascript code that I am using to popup a window with an embedded iframe:

	// Create a prepopulated iframe to the Contact from GHL
$(document).on('knack-scene-render.scene_191', function(event, scene) {
    var profile_Link = Knack.models['view_321'].toJSON().field_472;
    $('iframe').attr('src', profile_Link);

});

I can click the link to fire that code once but the second time I go to click the link the window pops up with the swirling icon and won't load and then the KTL wait alert pops up

**Comment by djbbiz** [comment] 2023-08-04 18:41
Not sure that this is a KTL issue or a Knack issue as there is no unusual error when the first Window is popped up but as I said when the second window is popped up is when the problem happens. This is the error that is popping up in the browser console:

k_2d7a0a450612cd71163b863a7bf765ce9ce17c0a.js:587 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://us-gov-west-1-renderer-read.knack.com') does not match the recipient window's origin ('https://sixsigfit.knack.com').

**Comment by cortexrd** [comment] 2023-08-06 18:06
> I am getting this message every few minutes now. Any idea why?

The green popup you see if the KTL's **spinnerWatchDog**.  

It is trigged when the spinner is looping for more than 50 seconds.
The default is **spinnerCtrDelay - 10 seconds**  (spinnerCtrDelay = 60).

Now why is this happening - that's the big question.  What you see is just the symptom.

BTW, you can disable the spinner watchdog by adding these lines in your code:

```
ktl.core.setCfg({
    enabled: {
        spinnerWatchDog: true,
    },
})
```

But that's just an emergency and temporary patch to bypass the problem until we find the root cause.

The console logs don't seem to be related to the KTL, but it remains to be proven so.

Norm

**Comment by djbbiz** [comment] 2023-08-07 00:17
It had something to do with a cross browser origin issue because I have dynamically spinning up an iFrame with javascript, it seemed to be getting confused about which site it was on. I decided to switch over to an iFrame that was embedded in a text link and display that in a details view using a modal popup. The styling is a bit more restrictive, but it works fine now.

**Comment by cortexrd** [comment] 2023-08-07 16:47
Glad you got it working... glad it wasn't the KTL!
Closing this now,
Norm

**Closed by cortexrd** 2023-08-07 16:47 UTC
