### ISSUE TITLE
Additional time for uploads

### ISSUE THREAD

**Issue by bkimbro1972** [cortexrd/Knack-Toolkit-Library#103] opened 2023-09-18 13:59 UTC
I was curious if there is a way to make it so that the library would allow for a longer time for uploading larger files?  A user has a slower internet connection and when she uploads a larger file, it ends up not allowing this.  It reloads the page after a countdown.  This does not allow her to upload the larger files.  If I take the KTL code out, it will allow her to upload all the files.  I just was curious if you had run into this before.**

**Comment by cortexrd** [comment] 2023-09-18 14:27
Hi Brian,

Thanks for reaching out and reporting this issue.  You are right, this is a use case that must be addressed.

I'd love to predict how long an upload will take, but since it's not possible, the other option is to get around the problem.

There are several ways to achieve this, here they are.

1. disable the spinner watchdog.  Far from being ideal, this would be your last choice.
2. increase the timeout delay value.  Again, this might help in many cases, but depending on the file size, your connection speed and Knack's server contingency, it may not always work.
3. the ultimate solution is to disable the spinner watchdog for specific scenes

Assuming you'd go for option 3, you must first add the content of this file to your Javascript pane, below the loader:  [https://github.com/cortexrd/Knack-Toolkit-Library/blob/dev/KTL_Customization.js](url)

Then add these lines just before the comment:  `//KTL Setup - END`

```
ktl.scenes.setCfg({
    spinnerWdExcludeScn: ['scene_1'], //These scenes take longer, so let them go for as long as needed.
});
```

Replace the `scene_1` by yours (keep quotes).  If you have more than one, just add them, separated by commas.


You end up with something that looks like this:

```
//This file is a template that shows how to customize the KTL for your application.
//Insert the code below in the Javascript pane of your app's Builder, just after the loader code.
//Once the KTL is done loading, it will jump in the ktlReady function and apply your desired settings.
//All code must be located inside the ktlReady section.
//See GitHub's Wiki for more details.

//Your app's version.
window.APP_VERSION = '1.0.0';

window.ktlReady = function (appInfo = {}) {
    var ktl = new Ktl($, appInfo);

    //KTL Setup - BEGIN
    ktl.scenes.setCfg({
        versionDisplayName: 'MyApp', //Short version of your app name. Leave empty to hide it. Comment whole line for actual app name.
    })

    ktl.core.setCfg({
        developerNames: ['Firstname Lastname'], //Add your name here to get super powers!

        //Main KTL feature switches.  Here is where your App can override the defaults and enable/disable the features.
        enabled: {
            //"Basic" features
            //Enabled by default. To disable them, their flag must exist and be set to false.
            versionInfo: {
                viShowAppInfo: true,
                viShowKtlInfo: true,
                viShowToRoles: ['Developer'], //Array of Account Roles strings who can see the version info bar. Leave empty for all.
                viPosX: 'right', //right, center, left
                viPosY: 'top', //top, bottom
                viPosXMobile: 'center', //right, center, left
                viPosYMobile: 'bottom', //top, bottom
                viOpacity: 50, //0 to 100
                viOpacityHover: 100, //0 to 100
            },

            showMenuInTitle: true,
            selTextOnFocus: true,
            inlineEditColor: true,
            rowHoverHighlight: true,
            chznBetter: true,
            autoFocus: true,
            sortedMenus: true,
            userFilters: true,
            persistentForm: true,
            calendarGotoDate: true,
            rememberMe: true,
            formPreValidation: true,
            spinnerWatchDog: true,
            idleWatchDog: true,
            debugWnd: true,
        },
    });

    ktl.scenes.setCfg({
        spinnerWdExcludeScn: ['scene_1'], //These scenes take longer, so let them go for as long as needed.
    });
    //KTL Setup - END


    //KTL callbacks to your App - BEGIN
    //KTL callbacks to your App - END

    /////////////////////////////////////////////////
    //Your App-specific code goes here...

}
```

As you can see, the KTL is highly customizable.  If this works for you, please close this issue.

Enjoy,
Norm

**Comment by bkimbro1972** [comment] 2023-09-18 16:40
Thank you.  This seems to have fixed my upload issue.  Before I used the default script and the editable items were a different color and when I hovered over a row it would highlight it.  Do you know how can I turn these back on?  Thanks

**Comment by cortexrd** [comment] 2023-09-19 17:32
Brian,

Glad it solved your issue.  

BTW, I've created a **new keyword** that does the same thing, without having to add the config code above.
It's the **_nswd** for **No Spinner WatchDog**.

You need to add **just one instance of this keyword to any view** in your scene and it will prevent interruptions when the system is busy for a long time.

You can leave the code in if you want, or use the keyword.  It's just the same.

About your colors issue, I'm not sure sure why it would do that.  I can't reproduce the bug here.  It is related to these variables: 1. inlineEditColor and rowHoverHighlight (both should be true)
2. inlineEditBkgColor and tableRowHoverBkgColor (both should match your app's header color, but washed-out)

Can you create a dummy page for me to log-in and do some tests?  I need a grid with inline editing and a few records.  Use this email:  nd@ctrnd.com.   Send me a temporary login pw there.

Norm

**Closed by cortexrd** 2023-09-19 17:32 UTC
