### ISSUE TITLE
View disappears if a form has _ro and a file is added

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#219] opened 2024-02-04 15:35 UTC
Hi @cortexrd 

I am using _ro on a form that also has a file field. 

The _ro works as expected on load.  However, when adding a file, the whole view disappears and ktlVisabilityHidden is on the view.  The view doesn't rerender.  I think the promise is not getting resolved.

I'm trying to see why this is happening, but I am not too familiar with the mutation observer part of the KTL.

Craig

**Comment by cortexrd** [comment] 2024-02-04 20:49
Just to explain a bit more on this, the line:

`keywords._ro && $('#' + viewId).addClass('ktlVisibilityHidden');`

is there to hide the view until all _ro processing is settled.  Otherwise, you have options briefly visible and we don't want that.

So I added some protection against File Uploads.  We will certainly need to add similar exceptions as we find them in the future.

Give it a try in dev mode.

Norm

**Comment by cortexrd** [comment] 2024-02-04 20:50
The mutation observer is simply a method to be notified when the DOM changes (added or removed nodes), so we can take action.

ND

**Comment by CSWinnall** [comment] 2024-02-04 20:55
Thank you Norm.  It works now

**Comment by cortexrd** [comment] 2024-02-04 20:58
Released in v0.22.17

**Comment by Greenlight88** [comment] 2024-02-11 02:32
Hey guys experiencing similar issue (using latest 0.22.20) my use is a very straight forward application of it and there are no files on the form

my code: _ro=Payment Terms, Account Locked

Applied to a Create Entry Form

Payment Terms is a required field, Multiple Choice, drop down one selection with Custom Sorting and a Default value set to 'Prepay'

The 'Account Locked' option is new and hasnt actually been applied to any accounts as yet

Code is applied in the Description of the form

THe form briefly renders and then dissapears entirely

THere are display rules on the form but none that affect every field

**Comment by CSWinnall** [comment] 2024-02-12 07:37
Hi @Greenlight88 

Could you send a screenshot of the form you are having the issue with?  Is the Payment Terms hidden when the form loads?

Craig

**Comment by Greenlight88** [comment] 2024-02-12 13:36
Hi Craig,

I made you a video - 



https://github.com/cortexrd/Knack-Toolkit-Library/assets/136812384/ab08a6d9-8558-4196-9a2e-9bf8ff8c883b

I also played around with it a bit - I found out it has nothing to do with the field being required, or the custom sorting - I tried removing a different option instead of Account Locked, same result

YOu can't see it in the video but I moved the field up in another test and confirmed that the Payment Terms field is visible before the form dissapears

**Comment by cortexrd** [comment] 2024-02-13 00:41
Hi guys,

This issue is the same again, where we hide the view completely to prevent showing up stuff we want to keep hidden until settled.  The solution is not trivial.  

We'll need to add more exceptions as we find them.
I can't see any other option because the _hide-view events_ happen **after** we've _un-hidden_ the view.

@Greenlight88 
Can you try to copy the view elsewhere (or in same page) and remove one field at a time to pinpoint which one has the adverse effect, please?


@CSWinnall   Here's where the problem lies:

```
if (keywords._ro) {
    //Process exceptions that cause unwanted view disappearance.
    if (!mutRec.target.classList.contains('kn-asset-current')) //File Uploads
        keywords._ro && $('#' + viewId).addClass('ktlVisibilityHidden');
}```

@Greenlight88 
I'd like to schedule a live debugging session.  Is it possible and when?
Email me at nd@ctrnd.com

Norm

**Comment by cortexrd** [comment] 2024-02-14 04:06
@Greenlight88,

Can you test the dev version please?  I've added a temporary patch that shows back the view after 3 seconds.  Let me know if it works.

This is temporary until I find a good solution.

FYI, you can also force showing any **hidden** elements by clicking in the KTL Developer Tools popup, on the **Hidden Elements**.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/ab65ff17-e836-47e9-b493-e2f55e2fe4fa)

Can be useful to troubleshoot.

Norm

**Comment by Greenlight88** [comment] 2024-02-15 14:12
Hey Craig and Norm ,

Following some of Norms suggestions resolved the issue - I think the View was corrupted in some way. WHen I copied the view it did not work in the same way the original form did not work but after selectively deleting fields and saving and retrying it did work and then when I added same fileds back in and saved it still worked 

Trying the same process on the original form did not give the same result

Any way long story short there is nothing about the particular fields that cause an issue, just some sort of corruption probably because of copying a view between pages which is a problem I've had in the past

I've kept the original form in place in case you wanted to look at it at all theres a side by side form which is identical - working and not working

Original (doesnt render)
https://greenlightservices.knack.com/greenlight-online#companies4/add-company3/

Copy (works)
https://greenlightservices.knack.com/greenlight-online#companies4/add-company-22/

**Comment by cortexrd** [comment] 2024-02-15 15:00
Very interesting, I can see the problem and debug at will now - thanks.

I will investigate that later.

Norm

**Comment by CSWinnall** [comment] 2024-03-06 07:48
Hi Norm

I think I have figured out some of the intermittant issues with _ro.  Chrome extensions that get added to the dom i.e. Microsoft Spell Checker, or Auto fill apps that add an icon:

After the mseditor squiggle gets added to the dom, see below, the view disappears:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/c2ebef82-5525-43ce-9223-12cef869fa20)

This is intermittant depending on how good I am at spelling.

My boss uses an auto fill app that adds an icon after the page loads, the view disappears for him.

Craig

**Comment by cortexrd** [comment] 2024-03-06 18:30
Yes, that's another situation where the code will break.

We really need to find another method to preemptively hide the view until all keywords are done processing.
Last night, I may have found a solution that will do the job.  It would allow to completely discard that problematic code.

Will keep you posted,
Norm

**Comment by CSWinnall** [comment] 2024-03-06 18:32
Ok great thank you.

**Comment by cortexrd** [comment] 2024-03-07 03:55
Hi guys,

Ok, I might have found the solution.

I've coded something really cool that will probably fix a lot of similar issues, since they're all related to the same thing:  the MutationObserver.

There's simply no such thing anymore!

All is replaced by very different and much simpler, cleaner code inspired by David Roizenman's code on Slack here:
https://knack-community.slack.com/archives/C016QKN0QBF/p1707364683629919

I've uploaded the Beta code so you can test it.

Let me know if it works,
Norm

**Comment by CSWinnall** [comment] 2024-03-07 06:53
Hi Norm 

This is working well

Thank you

**Closed** 2024-03-07 13:25 UTC
