### ISSUE TITLE
Wait screen causing delays

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#265] opened 2024-03-10 07:54 UTC
I have been seeing the green wait screen a lot lately. It appears to me like maybe a server issue for the toolkit but maybe there is something in my code that is causing it. Can you shed any light on why this is constantly happening every time I submit a form?

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/eb96292e-9dd7-4e4b-9060-2be4477fb043)

**Comment by cortexrd** [comment] 2024-03-10 14:44
Hi Dean,

Did you check the console logs?  Errors will cause that, and it would be easy to spot and fix.

FYI, that green popup is what we call the Spinner Watchdog.  You can customize this as you want regarding the timout delay and countdown, and of course, you can disable it.

It is triggered by the spinner's presence (visiblity), either in the center of the screen (large one we all know too well) and the smaller one that appears on the Submit buttons.  As soon as one or the other shows up, we start counting down from 60s to zero.  At 50s, we popup the "patience prompter" that displays how much time remains before the forceful page reload.

Now the question remains:  does it mostly ends up with a successful submit, or does the WD timeout kicks in with a page reload?  Does it always happen or, something like 50% of the time?

Any new information will help.

Norm

**Comment by djbbiz** [comment] 2024-03-10 17:42
The submit is successful the the message keeps popping up and there are very few errors in the console but there is one that isn't displaying anything:
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/6e4b84bf-1346-41dc-bc0a-f607cf9d9184)

**Comment by djbbiz** [comment] 2024-03-10 17:43
Here is the source for the unexplained error 
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/64454532/66219e5c-c39b-4276-8706-cef9e5a97b74)

**Comment by djbbiz** [comment] 2024-03-10 18:26
I think I found the source, I had a page that is being used for an API GET request that wasn't available to all the roles and should have been. I am not sure why it wasn't showing in one browser but I found it in another Chrome instance I created. Thanks for letting me know what this error means, as I wasn't seeing an error at first and didn't know to look for it.

**Comment by cortexrd** [comment] 2024-03-11 04:23
Great!  I'm glad you found the cause of your issue.
I will close this and if you find something else, feel free to re-open.

Cheers,
Norm

**Closed as completed by cortexrd** 2024-03-11 04:23 UTC
