### ISSUE TITLE
Collapsed columns and keyword search

### ISSUE THREAD

**Issue by DeejaySentinel** [cortexrd/Knack-Toolkit-Library#286] opened 2024-04-29 15:32 UTC
Currently I have collapsed columns functionality turned on globally within my application. If I go to a table and collapse a few columns and then save the view, I will then type in a search term in the "Keyword Search" field and the columns will then expand. After that point I cannot get the columns to collapse again with the "button". I go to different screens and then come back to the original screen with the saved view and still it does not work.

UPDATE: It seems to me that the issue resides in the fact the the search keywords, filter and collapsed columns are all tied to the button. It would be nice is the collapsed columns was a separate saved button thus not being affected by changed filters or keyword searches.

**Comment by cortexrd** [comment] 2024-05-09 14:56
Hi @DeejaySentinel,

I'll look into this.

But you're right, the User Filter buttons have been designated as the placeholder for the collapsed columns information, as they are seen as part of the filtering process where you want to reduce the visual noise and be able to recall all these presets quickly.

This is by design and will not change, as it would force the creation of a whole new set of buttons, undo and rework on a lot of complex code, etc.

Once this bug is fixed, we can discuss this furthermore, and see if it's still too annoying.  Then we can always come up with a new setting that improves the user experience.

Norm

**Comment by DeejaySentinel** [comment] 2024-05-09 17:59
Thanks for the info. I don’t really think it needs to change as long as the bug is fixed. I really love the collapsed columns and it allows me to keep my data on one line but still have the flexibility to open up those columns if need be.

--
Thank you,

DEE JAY SKINNER
600 CORPORATE CIRCLE | GOLDEN, CO 80401
***@***.******@***.***>
www.sentinelsystems.com<https://www.sentinelsystems.com>

[cid:42937DF2109B469E9A7E165B7C96C87E]

[cid:88F08B0BEF9C4785B61638CDE26C0DA7]
On May 9, 2024 at 7:56 AM -0700, Cortex R&D Inc. ***@***.***>, wrote:

Hi @DeejaySentinel<https://github.com/DeejaySentinel>,

I'll look into this.

But you're right, the User Filter buttons have been designated as the placeholder for the collapsed columns information, as they are seen as part of the filtering process where you want to reduce the visual noise and be able to recall all these presets quickly.

This is by design and will not change, as it would force the creation of a whole new set of buttons, undo and rework on a lot of complex code, etc.

Once this bug is fixed, we can discuss this furthermore, and see if it's still too annoying. Then we can always come up with a new setting that improves the user experience.

Norm

**Comment by cortexrd** [comment] 2024-05-20 13:24
Hi @DeejaySentinel,

We have a fix now.  You can try it out in the Beta code.

Let me know if it works as expected,
Norm

**Comment by DeejaySentinel** [comment] 2024-05-20 20:48
Hello Norm,

Where is the information that I would need to test beta code?

--
Thank you,

DEE JAY SKINNER
600 CORPORATE CIRCLE | GOLDEN, CO 80401
***@***.******@***.***>
www.sentinelsystems.com<https://www.sentinelsystems.com>

[cid:B4F8FB0B3B71412D986C9C4CC7BE2519]

[cid:2C68E26F3CA74C8E9AC4A7ACC6244183]
On May 20, 2024 at 6:24 AM -0700, Cortex R&D Inc. ***@***.***>, wrote:

Hi @DeejaySentinel<https://github.com/DeejaySentinel>,

We have a fix now. You can try it out in the Beta code.

Let me know if it works as expected,
Norm

**Comment by DeejaySentinel** [comment] 2024-05-20 23:20
I’ve tested the code and at first it seemed like it was working good and then I started to have an issue with a column that I am hiding with the “_hc” keyword. Please watch video for issue.
https://www.loom.com/share/bed404af25b145c1a5750559ff748fe3?sid=b7483049-c95c-4903-8d19-60e0005199d4

--
Thank you,

Dee Jay Skinner
On May 20, 2024 at 6:24 AM -0700, Cortex R&D Inc. ***@***.***>, wrote:

Hi @DeejaySentinel<https://github.com/DeejaySentinel>,

We have a fix now. You can try it out in the Beta code.

Let me know if it works as expected,
Norm

**Comment by cortexrd** [comment] 2024-05-21 12:12
@DeejaySentinel,

That's a new one, I will investigate this.

There's another issue where, if you have no user filter active and you collapse columns, then do a search, you lose the collapsed states.

Norm

**Comment by cortexrd** [comment] 2024-05-25 03:36
Hi @DeejaySentinel,

I've made a release **v0.25.0** today with lots of code changes that could potentially solve this.
Can you retest with this version and tell me if you still have the bug in the video please?

If still there, I'll try to fix it this weekend.

Norm

**Comment by DeejaySentinel** [comment] 2024-05-25 14:28
Norm,

The issue with the notes field showing is now resolved. There is one bug that you can see in this video but everything else seems to be working properly.

https://www.loom.com/share/2cdc6438553f49bda98aa59bdcb077f9?sid=340b2743-b2b7-4fd8-8e61-e48f0712f4a9

--
Thank you,

Dee Jay Skinner
On May 24, 2024 at 8:37 PM -0700, Cortex R&D Inc. ***@***.***>, wrote:

Hi @DeejaySentinel<https://github.com/DeejaySentinel>,

I've made a release v0.25.0 today with lots of code changes that could potentially solve this.
Can you retest with this version and tell me if you still have the bug in the video please?

If still there, I'll try to fix it this weekend.

Norm

**Comment by cortexrd** [comment] 2024-05-25 14:59
It's related to the question mark in Billable.

I will fix that easily, but not today.

Good catch - thanks!!!
Norm

**Comment by DeejaySentinel** [comment] 2024-05-25 15:01
Great thanks

--
Thank you,

Dee Jay Skinner
On May 25, 2024 at 7:59 AM -0700, Cortex R&D Inc. ***@***.***>, wrote:

It's related to the question mark in Billable.

I will fix that easily, but not today.

Good catch - thanks!!!
Norm

**Comment by cortexrd** [comment] 2024-05-26 17:09
@DeejaySentinel,

Can you test Beta please?
If good, you can close this issue.

Norm

**Comment by DeejaySentinel** [comment] 2024-05-26 18:51
Yes all looks great. Thank you

--
Thank you,

DEE JAY SKINNER
600 CORPORATE CIRCLE | GOLDEN, CO 80401
***@***.******@***.***>
www.sentinelsystems.com<https://www.sentinelsystems.com>

[cid:C20FD701617C41B49553F0337D3356C3]

[cid:CF9636F9B47A4B9D8A618F1E01FC48B1]
On May 26, 2024 at 10:09 AM -0700, Cortex R&D Inc. ***@***.***>, wrote:

@DeejaySentinel<https://github.com/DeejaySentinel>,

Can you test Beta please?
If good, you can close this issue.

Norm

**Comment by DeejaySentinel** [comment] 2024-05-26 18:54
Tested the beta and column collapsing seems to be working as intended. Thank you for the update.

**Closed as completed** 2024-05-26 18:53 UTC

**Comment by cortexrd** [comment] 2024-05-26 19:04
I've released a prod version:  **v0.25.1** that you can use now.
Norm

**Comment by DeejaySentinel** [comment] 2024-05-26 19:24
Ok thank you

--
Thank you,

DEE JAY SKINNER
600 CORPORATE CIRCLE | GOLDEN, CO 80401
***@***.******@***.***>
www.sentinelsystems.com<https://www.sentinelsystems.com>

[cid:84EB7E9069EB462D8DA5A7EB97022B2E]

[cid:1E671AEE83664B0497FF04205C31383A]
On May 26, 2024 at 12:05 PM -0700, Cortex R&D Inc. ***@***.***>, wrote:

I've released a prod version: v0.25.1 that you can use now.
Norm
