### ISSUE TITLE
API failures related to Knack date/Time format change

### ISSUE THREAD

**Issue by Greenlight88** [cortexrd/Knack-Toolkit-Library#416] opened 2024-11-27 06:57 UTC
Hi Norm and all - this just started happening this afternoon - I hadnt changed any aspects that would affect the relevant fields

Error message from KTL is

![image](https://github.com/user-attachments/assets/d1fbd4be-f931-4128-88f6-dfdb54d0b4cb)

The field mentioned there is the Date Time Field for  App Settings and there is another error message that comes up for the User Filters in the iFrameWnd View

Noting - I am in Australia and we do our dates the other way  DD/MM/YYYY (which you know, makes a lot more sense) - I set all date fields up as per your instructions though MM/DD/YYY and military time - defaults to both current date and current time

I really don't  think I did anything to cause this - if other people aren't  noticing a similar bug I'm  thinking it might have something to do with local time formats??

I have no idea

**Comment by Greenlight88** [comment] 2024-11-27 06:59
It throws up a constant 2 x errors every 15 seconds or so, doesn't  seem to affect users, though I imagine they can’t  save new filters

**Comment by Greenlight88** [comment] 2024-11-27 07:00
Using knack version 0.29.2

**Comment by CSWinnall** [comment] 2024-11-27 07:43
Hi @Greenlight88 

It looks like Knack have been messing with the date/time fields which is causing this issue. @cortexrd I have had set:
`iFrameWnd: false` in my local env. to stop this error from occurring.

Craig

**Comment by CSWinnall** [comment] 2024-11-27 07:49
This is what Knack say:

Date/Time Fields: Date/Time fields using calendar options now accept ISO-8601 timestamps when specifying "from" and "to" dates, regardless of the selected field format. For example, values like "2024-11-26T16:15:00.000Z" can now be used for these fields, providing more flexibility in formatting.
End-User Impact: This release simply accepts an additional date/time format and no action is necessary.
Date/Time & Equation Fields > Time Format Setting: When a Date/Time field (or an Equation field with Equation Type = Date and Result Type = Date) has the "Time Format" set to "Ignore Time” in the field’s settings, this setting is now uniformly applied. Previously, the time component might still be stored on the backend and included in API responses. With this update, API responses for these fields will always show the time as 12:00 am (midnight).
End-User Impact: API integrations, third-party tools like Zapier and Make, and other equation fields that utilize a date field may need adjustments if they rely on the previously stored time component. To preserve time values, please choose a specific time format (12-hour or 24-hour) instead of "Ignore Time” in the field’s settings.
Date Equations: While editing date equation field settings, users will no longer be able to set the Date Type to "hours" if the result of the equation has the Time Format set to "Ignore Time". By default, Date Equation fields that have "Ignore Time" set will have "Days" selected for the Date Type.

**Comment by Greenlight88** [comment] 2024-11-27 08:43
I actually noticed this in another context some of the date time fields in our automations started erroring

our input Dates formatted as "DD/MM/YYYY HH:mm A" started erroring and we had to change to this format: "DD/MM/YYYY h:mma"

So **27/11/2024 07:14 PM** must now be **27/11/2024 7:14pm**

Way to make a minute change of no benefit that will cause humongous headaches!

**Comment by Greenlight88** [comment] 2024-11-27 08:57
Ok just reading what Craig wrote there - Some of the filters we made use an 'after this date' and we set to ignore time - I will test if issue resolves if I adjust those filters

**Comment by Greenlight88** [comment] 2024-11-27 09:05
Nope - that didn't work - Also as an aside I've had the issue before of knack setting the time to 12:00 AM with the date causing the date to be read as the previous day in other environments, 


I'll switch my iFrameWnd off now too, thanks Craig

**Comment by CSWinnall** [comment] 2024-11-27 09:47
Hi

The issue is that the KTL is making an api call and is trying to input the date time into a field in the iFrameWnd and the date/time is not being recognised.

Thanks for the heads up about Make.com.  I agree this could be a real headache as we have over 100 scenarios to go through and make sure none have an error in them.

Craig

**Comment by Greenlight88** [comment] 2024-11-27 10:30
Hey Craig I have to fix ours in Make too - in Make you can set custom fields _ I'm  going to create a field: make_time_format and then input this into all the different areas - then if they ever do this again Ill change in one place not ... Probably 400 places for me - I'm  goiung to think about using that approach wherever it makes sense moving forward

**Comment by Greenlight88** [comment] 2024-11-27 10:35
Also I'm sure you're up on advanced techniques, but for anyone else with  this challenge, in make you can download a footprint of any scenario, do a search and replace and then reupload it - then bingo bambo all date formats are updated in that scenario - more secure and thorough and much faster - if only that could be done across all scenarios!

**Comment by cortexrd** [comment] 2024-11-27 14:06
Hey guys,

I've just seen this now.  I will tackle the issue right away.

Norm

**Comment by MickGraham23** [comment] 2024-11-27 20:54
I have 3 MAKE scenarios erroring out on Date Fields.  They are just date DD/MM/YYYY and same in Knack.   Not sure what to do to fix?   

I have iframwnd to false.

**Comment by Greenlight88** [comment] 2024-11-27 22:29
Hey Mick - I'm  just guessing here - but betting you need to reformat the field to have time included (even though field has no time) try formatting date to DD/MM/YYYY h:mma. If its only some Scenarios but not others I would go and have a look to see what is different about the relevant date fields

**Comment by Greenlight88** [comment] 2024-11-27 22:43
Just tested that and while it stops the error, the date comes through to knack as blank - looking in to further - @CSWinnall any thoughts here?

**Comment by Max-Pigs** [comment] 2024-11-27 23:17
adding to the thread that this is happening to my site as well.

**Comment by Greenlight88** [comment] 2024-11-28 00:36
My apologies - correction to the above - correct format for Make.com seems to be **DD/MM/YYYY hh:mma**

**Comment by cortexrd** [comment] 2024-11-28 02:18
Hi to all,

I've released a hotfix for that problem.
Can you try it out please?   It's in **Dev** code for now.

As soon as I have more confirmation, I'll release in Prod.

Thanks for your patience.
Norm

**Comment by cortexrd** [comment] 2024-11-28 03:04
I've just deployed **KTL v0.29.4** in production.
Hope it addresses all the use cases.
Let me know as soon as you see some errors or anything abnormal.

Norm

**Comment by Greenlight88** [comment] 2024-11-28 05:17
I'll try it now

**Comment by Max-Pigs** [comment] 2024-11-28 05:25
Hey @cortexrd! Thank you as always for your speedy response here. I cannot for the life of me get 29.4 to load. I am stuck in 29.3. I tried hard refresh, clearing my cache, new tabs ect. Any idea?

**Comment by Greenlight88** [comment] 2024-11-28 05:30
Yes that seems to have fixed it!

I tested both the fields that were erroring before in ifame Wnd - public Filters and User Prefs by creating new filters in each - date updates correctly now

![Screenshot 2024-11-28 162900](https://github.com/user-attachments/assets/0d04b5dd-8ebb-4368-a434-abf785e6747d)

**Comment by Max-Pigs** [comment] 2024-11-28 05:39
> Hey @cortexrd! Thank you as always for your speedy response here. I cannot for the life of me get 29.4 to load. I am stuck in 29.3. I tried hard refresh, clearing my cache, new tabs ect. Any idea?

Nevermind. this was user error. There was a manual code version selected in our code. Updated now, testing for errors now

**Comment by cortexrd** [comment] 2024-11-28 05:46
Gosh... you got my heart racing again for a while - LOL!!!
But I'm very happy to see it seems to be resolved now.

Thanks for your input, I'll sleep better tonight!!
Shall we close this one?

Norm

**Comment by Greenlight88** [comment] 2024-11-28 06:10
Absolutely Thanks Norm!

**Closed as completed** 2024-11-28 06:09 UTC
Labels: bug
