### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by chprojectsupport** [cortexrd/Knack-Toolkit-Library#217] opened 2024-02-02 19:35 UTC
Hi Guys, after conneting with Norm a couple of weeks ago he mentioned that the very talented Craig Winnall (who I also had the pleasure of meeting last weekend) created the _ttip Tooltip keyword 👍
I have recently intorduced KTL to an existing client who has been using some of the functions and added _ttip to a few fields so they could show the tip on tables, lists, forms and views. This all worked as expected except the tool tip doesn't have a solid backgound on a details view like it does on a table. On a detail view the ttip is transparent.
Are we doing something wrong or is this a bug?
![Tooltip Issue](https://github.com/cortexrd/Knack-Toolkit-Library/assets/130801992/d401935a-a24f-4931-872c-7e95eb212f6e)

**Comment by CSWinnall** [comment] 2024-02-02 20:44
Hi Carl I'll look into this.  It should work with just the _ttip keyword.  There is functionality to use your own colours but the default should be dark background & white text.

**Comment by CSWinnall** [comment] 2024-02-02 20:58
Hi Carl

Could we arrange a quick chat tomorrow or Sunday?  
I have tested the default styles here and it seems to be working.  

Craig

**Comment by chprojectsupport** [comment] 2024-02-02 21:18
Yes, tomorrow morning would be good. Can you send me a Zoom invite for 10am to carlholmeschps@gmail.com please 👍

**Comment by cortexrd** [comment] 2024-02-03 13:08
Hey guys,

I've been trying to reproduce this bug but I can't do it in my KTL Tutorial demo app.

Here's what I have in the field's description for Store:

`_ttip=[This tooltip is for Store], [dtfl]`

I have the ttip and it works just fine:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/47be9270-8909-460b-845f-73d18acea3f6)

What am I doing _**wrong**_ - I've gotta see that bug (!!! LOL)

Norm

**Comment by CSWinnall** [comment] 2024-02-03 13:12
It is a problem with list views I've done a PR to fix it.

**Comment by cortexrd** [comment] 2024-02-03 13:16
I know, that's why I need to reproduce the bug first:  to **prove to myself** that your fix actually works.  Just a good practice.  Never take anything for granted.  And sometimes, in the process, you can discover other use cases that no one saw.

So I found out that it is the legacy flag:  "Use Legacy Design Settings" that is my problem.
I am currently **ON**, and if I switch to OFF, I can see the bug.

Will test the PR now and approve.

Norm

**Comment by chprojectsupport** [comment] 2024-02-03 13:16
It is related to a List view as opposed to a Details view

Carl Holmes
Director
Mobile 07768 128128
www.chprojectsupportlimited.com

**Comment by cortexrd** [comment] 2024-02-03 13:17
Oh!  I saw this "This all worked as expected except the tool tip doesn't have a solid backgound on a details view like it does on a table. On a **detail view** the ttip is transparent."

In this case, you should edit your post to prevent confusion.

ND

**Comment by CSWinnall** [comment] 2024-02-03 13:19
No the issue was that details and lists use the same styles so when we add
the tooltips it didn't match the styles.  So I've made the view type for
lists = details for styling

Craig

**Comment by cortexrd** [comment] 2024-02-03 13:21
I see what you mean.

I can reproduce the bug now :)
And BTW, it's not related to the legacy flag.

ND

**Comment by CSWinnall** [comment] 2024-02-03 13:22
Thank you Norm it took me a little while to figure it out too.

Craig

**Comment by cortexrd** [comment] 2024-02-03 13:24
Approved and merged.
Will be part of next release in a few minutes.

Closing this issue now.
Norm

**Closed by cortexrd** 2024-02-03 13:24 UTC

**Comment by cortexrd** [comment] 2024-02-03 13:31
Ready now in **KTL v0.22.16**.
Enjoy,
Norm

**Comment by chprojectsupport** [comment] 2024-02-03 13:59
Thank you guys 🙏

All working fine now!

Carl Holmes
Director
Mobile 07768 128128
www.chprojectsupportlimited.com
